name: btk_todo
description: "BTK ."
version: 1.0.0+1

environment:
  # Mimimum Dart SDK sürümü
  sdk: ^3.5.3

# Uygulamanın çalışması için gerekli olan temel paketler
# Sadece dependencies bölümünde belirtilen paketler 
# Derlenmiş projeye dahil edilir
dependencies:
  # Flutter SDK'sının projede kullanılacağını belirtir.
  flutter:
    sdk: flutter
  # Cupertino stili iOS ikonları
  cupertino_icons: ^1.0.8

# Geliştirme ve test süreçlerinde kullanılır
# Uygulamanın çalışması sırasında gerekli değildir.
# Derlenmiş projeye dahil edilmez.
dev_dependencies:
  flutter_test:
    sdk: flutter
  # Linting & Code Quality
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
